name: Sync Demo Branch

on:
  push:
    branches:
      - main

jobs:
  sync-demo-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo branch
        uses: actions/checkout@v2
        with:
          ref: 'demo'

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'
          path: 'main-branch'

      - name: Sync files from main branch to demo branch
        run: |
          # Exclude the 'cypress-example/' and '.github/' directories
          rsync -a --exclude='/cypress-example' --exclude='/github' main-branch/ ./
          rm -rf main-branch/

      - name: List remotes
        run: git remote -v

      - name: Push changes to demo branch
        run: |
          git config --global user.email "peter@petermsouzajr.com"
          git config --global user.name "Peter Souza"
          git add .
          git commit -m "Update files from main branch"
          # Use the 'force' flag with push, and use the PAT for authentication
          git push origin demo
