name: Sync Demo Branch

on:
  push:
    branches:
      - main

jobs:
  sync-demo-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo branch
        uses: actions/checkout@v2
        with:
          ref: 'demo'
          token: ${{ secrets.DEMO_UPDATE_PAT }} # Use the PAT for checkout

      - name: Fetch changes from main branch
        run: git fetch origin main

      - name: Checkout main branch files excluding .github, cypress-example, and playwright-example
        run: |
          git checkout origin/main -- . ':!/.github' ':!/cypress-example' ':!/playwright-example'

      - name: Find last merged branch
        id: last-merged-branch
        run: |
          git fetch --all
          last_branch=$(git log -1 --pretty=format:"%s" | awk -F 'from ' '{print $2}')
          echo "branch=$last_branch" >> $GITHUB_OUTPUT

      - name: Commit and push changes to demo branch
        run: |
          git config --global user.email "peter@petermsouzajr.com"
          git config --global user.name "Peter Souza"
          branch_name=${{ steps.last-merged-branch.outputs.branch }}
          git commit -am "Sync changes from main branch to demo (merged from $branch_name)" || echo "No changes to commit"
          git push https://${{ secrets.DEMO_UPDATE_PAT }}@github.com/petermsouzajr/qa-shadow-report.git demo
