name: Sync Demo Branch

on:
  push:
    branches:
      - main

jobs:
  sync-demo-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo branch
        uses: actions/checkout@v2
        with:
          ref: 'demo'
          token: ${{ secrets.DEMO_UPDATE_PAT }} # Use the PAT for checkout

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'
          token: ${{ secrets.DEMO_UPDATE_PAT }} # Use the PAT for checkout
          path: 'main-branch'

      - name: Sync files from main branch to demo branch, excluding .github
        run: |
          # Exclude the '.github/' directory
          rsync -a --exclude='.github/' main-branch/ ./
          rm -rf main-branch/

      - name: Check if secret is being read
        run: |
          if [ -z "${{ secrets.DEMO_UPDATE_PAT }}" ]; then
            echo "DEMO_UPDATE_PAT is empty"
            exit 1
          else
            echo "DEMO_UPDATE_PAT is not empty"
          fi

      - name: Commit and push changes to demo branch
        run: |
          git config --global user.email "peter@petermsouzajr.com"
          git config --global user.name "Peter Souza"
          # Add all changes except the 'cypress-example/' directory
          git add . -- ':!cypress-example'
          # Commit only if there are changes. The `||` operator will ensure the
          # command doesn't fail if there's nothing to commit.
          git commit -m "Update files from main branch" || true
          # Use the 'force' flag with push, and use the PAT for authentication
          git push --force https://${{ secrets.DEMO_UPDATE_PAT }}@github.com/petermsouzajr/cy-shadow-report.git demo
