name: Sync Demo Branch

on:
  push:
    branches:
      - main

jobs:
  sync-demo-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo branch
        uses: actions/checkout@v2
        with:
          ref: 'demo'

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'
          path: 'main-branch'

      - name: Sync files from main branch to demo branch, excluding .github
        run: |
          # Exclude the '.github/' directory
          rsync -a --exclude='.github/' main-branch/ ./
          rm -rf main-branch/

      - name: Commit and push changes to demo branch
        run: |
          git config --global user.email "peter@petermsouzajr.com"
          git config --global user.name "Peter Souza"
          # Add all changes except the 'cypress-example/' directory
          git add . -- ':!cypress-example'
          # Commit only if there are changes. The `||` operator will ensure the
          # command doesn't fail if there's nothing to commit.
          git commit -m "Update files from main branch" || true
          # Push the changes. No need to force push if you're not rewriting history.
          git push origin demo
